[package]
name = "rav"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
ffmpeg-sys-next = { version = "5.0.1" }
log = "0.4.14"
memmap = "0.7.0"
thiserror = "1.0.30"
