name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v2
      - name: update apt & upgrade
        run: sudo apt update --yes && sudo apt upgrade --yes
      - name: install ffmpeg dev libs
        #   /usr/bin/ld: cannot find -lGL
        #   /usr/bin/ld: cannot find -lSDL2
        #   /usr/bin/ld: cannot find -lbs2b
        #   /usr/bin/ld: cannot find -llilv-0
        #   /usr/bin/ld: cannot find -lsratom-0
        #   /usr/bin/ld: cannot find -lsord-0
        #   /usr/bin/ld: cannot find -lserd-0
        #   /usr/bin/ld: cannot find -lrubberband
        #   /usr/bin/ld: cannot find -lmysofa
        #   /usr/bin/ld: cannot find -lflite_cmu_time_awb
        #   /usr/bin/ld: cannot find -lflite_cmu_us_awb
        #   /usr/bin/ld: cannot find -lflite_cmu_us_kal
        #   /usr/bin/ld: cannot find -lflite_cmu_us_kal16
        #   /usr/bin/ld: cannot find -lflite_cmu_us_rms
        #   /usr/bin/ld: cannot find -lflite_cmu_us_slt
        #   /usr/bin/ld: cannot find -lflite_usenglish
        #   /usr/bin/ld: cannot find -lflite_cmulex
        #   /usr/bin/ld: cannot find -lflite
        #   /usr/bin/ld: cannot find -lfribidi
        #   /usr/bin/ld: cannot find -lass
        #   /usr/bin/ld: cannot find -lvidstab
        #   /usr/bin/ld: cannot find -lgme
        #   /usr/bin/ld: cannot find -lchromaprint
        #   /usr/bin/ld: cannot find -lbluray
        #   /usr/bin/ld: cannot find -lgnutls
        #   /usr/bin/ld: cannot find -lssh
        #   /usr/bin/ld: cannot find -lvpx
        #   /usr/bin/ld: cannot find -lzvbi
        #   /usr/bin/ld: cannot find -lcodec2
        #   /usr/bin/ld: cannot find -lgsm
        #   /usr/bin/ld: cannot find -lmp3lame
        #   /usr/bin/ld: cannot find -lopenjp2
        #   /usr/bin/ld: cannot find -lshine
        #   /usr/bin/ld: cannot find -ltwolame
        #   /usr/bin/ld: cannot find -lsoxr
        #   /usr/bin/ld: cannot find -lva-drm
        #   /usr/bin/ld: cannot find -lva-x11
        #   /usr/bin/ld: cannot find -lvdpau
        run: |
          sudo apt install --yes libavcodec-dev libavdevice-dev libavfilter-dev \
                                 libavformat-dev libavutil-dev libpostproc-dev \
                                 libswresample-dev libswscale-dev \
                                 libraw1394-dev libavc1394-dev \
                                 libiec61883-dev \
                                 libjack-dev libopenal-dev \
                                 libxcb-shape0-dev libxcb-xfixes0-dev \
                                 libcdio-paranoia-dev libcdio-paranoia-dev \
                                 libdc1394-22-dev libasound-dev \
                                 libcaca-dev libpulse-dev \
                                 libsndio-dev libogg-dev \
                                 libvorbis-dev libwavpack-dev \
                                 libwebp-dev libx264-dev libx265-dev libxvidcore-dev \
                                 libsnappy-dev libaom-dev libwebpmux3 libopus-dev \
                                 libspeex-dev libtheora-dev libczmq-dev libopenmpt-dev

      - name: setup rustup toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: build crates
        run: cargo build --verbose

      - name: test crates
        run: cargo test --verbose
