name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v2

      - name: install ffmpeg dev libs
        run: |
          sudo apt install --yes libavcodec-dev libavdevice-dev libavfilter-dev \
                                 libavformat-dev libavutil-dev libpostproc-dev \
                                 libswresample-dev libswscale-dev

      - name: setup rustup toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: build crates
        run: cargo build --verbose

      - name: test crates
        run: cargo test --verbose
